title: futuremaze
description: futuremaze add-on repository
logo: /kodi/repository.futuremaze/icon.png
theme: jekyll-theme-minimal
baseurl: /repository/
show_downloads: true
github:
    zip_url: https://github.com/Harekaze/repository/releases/download/3.0.0-kodi/repository.futuremaze.zip
defaults:
  -
    scope:
      path: "404.md"
    values:
      layout: "none"
plugins:
    - jekyll-seo-tag
    - jekyll-default-layout
    - jekyll-optional-front-matter
    - jekyll-titles-from-headings
    - jekyll-readme-index
    - jemoji
