title: Harekaze
description: futuremaze add-on repository
logo: /kodi/repository.futuremaze/icon.png
theme: jekyll-theme-minimal
baseurl: /libreelec_addon_repository/
show_downloads: true
github:
    zip_url: https://github.com/futuremaze/libreelec_addon_repository/releases/download/1.0.0-kodi/repository.futuremaze.zip
defaults:
  -
    scope:
      path: "404.md"
    values:
      layout: "none"
plugins:
    - jekyll-seo-tag
    - jekyll-default-layout
    - jekyll-optional-front-matter
    - jekyll-titles-from-headings
    - jekyll-readme-index
    - jemoji
